version: "3"

services:
  chess:
    build: chess/.
    image: 1081_final_chess
    container_name: chess_mix
    ports:
      - "8888:80"
    restart: always

  mask:
    build: mask/.
    image: 1081_final_mask
    container_name: mask_rsa
    ports:
      - "8889:1337"
    restart: always

  halloworld:
    build: halloworld/.
    image: 1081_final_halloworld
    container_name: halloworld_pt
    ports:
      - "8890:80"
    restart: always
  
  crazyfire:
    build: crazyfire/.
    image: 1081_final_crazyfire
    container_name: crazyfire_xss
    ports:
      - "8891:80"
    restart: always
